/*==================================================================================================
 * This file was generated by Gemini version 3 pro
 * All coments are made by Jacob Elliott
 *================================================================================================*/

import express from 'express'
import cors from 'cors'
import { getBooks, getBook, createBook } from './database/database.js'
import dotenv from 'dotenv'

dotenv.config()

const app = express()

app.use(express.json()) 
app.use(cors())

app.get("/books", async (req, res) => {
    const books = await getBooks()
    res.send(books)
})

app.get("/books/:id", async (req, res) => {
    const id = req.params.id
    const book = await getBook(id)
    res.send(book)
})

app.post("/books", async (req, res) => {
    const { title, author, contents } = req.body
    const note = await createBook(title, author, contents)
    res.status(201).send(note)
})

app.use((err, req, res, next) => {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})

app.listen(8080, () => {
    console.log('Server is running on port 8080')
})